### ISSUE TITLE
Analyse for Betaling

### ISSUE THREAD

**Issue by ivarne** [Altinn/app-lib-dotnet#334] opened 2023-11-03 08:21 UTC
### How do we store payment info?
* As a separate data element
* As DataValues on the instance
### Do we need a payment component?
* Payment is a separate task type, so it will likely be custom for the first version.
* First version redirects to payment providers UI.
### Common payment "app" for non Altinn App scenarios.
???
### Which providers should we support (Payex, dips, Nets...)
* First Nets Easy(Nets Checkout) Try to isolate everything Nets specific, but don't implement multiple to verify interfaces are correct.
### Role requirement payment?
* A separate task can have separate role requirements
### Process integration
* Payment should be a separate step.
### No fixed URL in apps? Is this ok as a return URL or not?
* Nets easy seems to be OK with custom urls everywhere.

**Comment by tjololo** [comment] 2024-01-19 15:02
Duplicate of #399

**Closed as not planned by tjololo** 2024-01-19 15:02 UTC
Labels: status/draft
